apiVersion: v2
name: ortelius
description: Ortelius
home: https://www.ortelius.io
icon: https://ortelius.github.io/ortelius-charts/logo.png
keywords:
- Service Catalog
- Microservices
- SBOM
type: application
version: 10.0.293
appVersion: 10.0.0
dependencies:
- name: ms-dep-pkg-cud
  version: 10.0.70
  repository: https://ortelius.github.io/ms-dep-pkg-cud/
- name: ms-dep-pkg-r
  version: 10.0.152
  repository: https://ortelius.github.io/ms-dep-pkg-r/
- name: ms-textfile-crud
  version: 10.0.49
  repository: https://ortelius.github.io/ms-textfile-crud/
- name: ms-compitem-crud
  version: 10.0.35
  repository: https://ortelius.github.io/ms-compitem-crud/
- name: ms-validate-user
  version: 10.0.50
  repository: https://ortelius.github.io/ms-validate-user/
- name: ms-scorecard
  version: 10.0.110
  repository: https://ortelius.github.io/ms-scorecard/
- name: ms-postgres
  version: 10.0.14
  condition: global.postgresql.enabled
  repository: https://ortelius.github.io/ms-postgres/
- name: ms-general
  version: 10.0.89
  repository: https://ortelius.github.io/ortelius/
- name: ms-nginx
  version: 10.0.89
  repository: https://ortelius.github.io/ortelius/
- name: ms-ui
  version: 10.0.89
  repository: https://ortelius.github.io/ortelius/
